#················································
# APP SETTINGS
#················································
NAME: My Project
ID: my-project
URL: http://localhost:8000
FORCE_URL: false
DYNAMIC_SUB_DOMAIN: false

#················································
# API-SERVER
#················································
#API_SERVER: false
API_SERVER:
  AUTH_CONTROLLER: HeaderController # external module
  SANITIZE_CONTROLLER: MyService.sanitize
  ALWAYS_200: false
  ROUTE_PERMISSION_FLAG: ⛊
  JSON_RESULT_INDICATOR: true # {success:1, data:json_data}

#················································
# API-CLIENT
#················································
API_CLIENT:
  "main":
    DNS: https://api.skent.com.br
    HEADER: API_HEADER # session[api_header][]

#················································
# FRONTEND BUILD
#------------------------------------------------
# File inclusion sequence
# Notes:
#   - FALSE, if API server is on
#   - FLOW_INNER: rules for builds inside parent build
#················································
#PAGES: false
PAGES:
  FILE_SEQUENCE:
    - <PAGE>.php
    - /inc-header.tpl
    - <PAGE>.tpl
    - /inc-footer-start.tpl
    - scripts.tpl

URL_MASK:
  .post: <PAGE>.post.php
  .run: <PAGE>.run.php
  .exec: <PAGE>.exec.php
  .css: <PAGE>.css
  .js: <PAGE>.js

#················································
# JOBS EVERY 1 MINUTE
#················································
JOBS:
  - src/jobs/demo.php

#················································
# AUTO INCLUDE LIBS (/* TO ALL)
#················································
# UNECESSARY?
AUTOLOAD:
  - modules/auth
  - modules/api
  - modules/mysql
  - modules/mail
  - src/libs/uitools
  - src/libs/helpers

#················································
# DEBUG FUNCTION
#------------------------------------------------
# If true, can be accessed by <url>/debug
#················································
DEBUG: true
